<?php
/**
 * Uninstall routine.
 *
 * Never deletes posts, pages, products, media or any content generated by AI.
 * Plugin settings are removed only if "Delete plugin settings on uninstall"
 * was enabled (off by default).
 *
 * @package AI_Content_Image_SEO
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

// Always stop background work.
wp_clear_scheduled_hook( 'ai_cis_process_bulk' );
wp_clear_scheduled_hook( 'ai_cis_process_auto' );
if ( function_exists( 'as_unschedule_all_actions' ) ) {
	as_unschedule_all_actions( 'ai_cis_process_bulk', array(), 'wbd-content-image-seo-assistant' );
	as_unschedule_all_actions( 'ai_cis_process_auto', array(), 'wbd-content-image-seo-assistant' );
}

$ai_cis_settings = get_option( 'ai_cis_settings', array() );

if ( ! is_array( $ai_cis_settings ) || empty( $ai_cis_settings['delete_on_uninstall'] ) ) {
	return;
}

foreach ( array( 'ai_cis_settings', 'ai_cis_api_keys', 'ai_cis_usage', 'ai_cis_bulk_job', 'ai_cis_auto_queue', 'ai_cis_auto_limit_hit', 'ai_cis_version' ) as $ai_cis_option ) {
	delete_option( $ai_cis_option );
}

foreach ( array( 'ai_cis_activation_redirect', 'ai_cis_bulk_lock', 'ai_cis_auto_lock', 'ai_cis_models_openai', 'ai_cis_models_gemini', 'ai_cis_models_anthropic', 'ai_cis_models_openrouter' ) as $ai_cis_transient ) {
	delete_transient( $ai_cis_transient );
}

// Internal processing flags only. SEO metadata and review summaries are user content and are kept.
foreach ( array( '_ai_cis_status', '_ai_cis_generated', '_ai_cis_image_type' ) as $ai_cis_meta_key ) {
	delete_post_meta_by_key( $ai_cis_meta_key );
}
